options:
  formatter : stylish

files:
  include : app/components/**/*.scss

rules:
  # Extends
  extends-before-mixins       : 2
  extends-before-declarations : 2
  placeholder-in-extend       : 2

  # Mixins
  mixins-before-declarations  : 2

  # Line Spacing
  one-declaration-per-line  : 2
  empty-line-between-blocks : 2
  single-line-per-selector  : 2

  # Disallows
  no-color-keywords        : 2
  no-color-literals        : 0
  no-css-comments          : 2
  no-debug                 : 1
  no-duplicate-properties  : 2
  no-empty-rulesets        : 2
  no-extends               : 0
  no-ids                   : 2
  no-important             : 1
  no-invalid-hex           : 2
  no-mergeable-selectors   : 1
  no-misspelled-properties : 2
  no-qualifying-elements   : 0
  no-trailing-zero         : 2
  no-transition-all        : 2
  no-url-protocols         : 2
  no-vendor-prefixes       : 2
  no-warn                  : 2
  property-units           : 0

  # Nesting
  force-attribute-nesting : 0
  force-element-nesting   : 0
  force-pseudo-nesting    : 0

  # Class name format
  class-name-format   :
    - 2
    -
      allow-leading-underscore : false
      convention               : hyphenatedbem

  # Variable name format
  variable-name-format   :
    - 2
    -
      allow-leading-underscore : false
      convention               : hyphenatedlowercase

  # Style Guide
  nesting-depth : 1
  quotes        : 2
  url-quotes    : 2
  zero-unit     : 2
  bem-depth :
      - 2
      -
        max-depth : 2
  border-zero :
      - 2
      -
        convention : none
  brace-style :
    - 2
    -
      style             : 1tbs
      allow-single-line : true
  clean-import-paths :
    - 2
    -
      leading-underscore : false
      filename-extension : true
  empty-args :
    - 2
    -
      include : true
  hex-length :
    - 2
    -
      style : short
  hex-notation :
    - 2
    -
      style : uppercase
  indentation :
    - 2
    -
      size : 2
  leading-zero :
    - 2
    -
      include : true
  property-sort-order :
    - 2
    -
      order : alphabetical
  shorthand-values :
    - 2
    -
      allowed-shorthands :
        - 1
        - 2

  # Inner Spacing
  space-after-comma     : 2
  space-after-colon     : 2
  space-before-brace    : 2
  space-before-bang     : 2
  space-after-bang      : 2
  space-between-parens  : 2
  space-around-operator : 2

  space-before-colon :
    - 2
    -
      include : true

  # Final Items
  trailing-semicolon : 2
  final-newline      : 2
